/*
 * This source file was generated by the Gradle 'init' task
 */
package org.firstProject;

import org.junit.Test;
import static org.junit.Assert.*;

// import org.firstProject.App;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
